# Generated by Django 3.0.1 on 2020-01-24 10:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('members', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, size=10)),
            ],
            options={
                'ordering': ['trip_name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('amt_from', models.CharField(max_length=30)),
                ('amount_to', django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=60, size=10)),
                ('amount', models.IntegerField()),
                ('trip_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip')),
            ],
        ),
    ]
